/** Shape of src/data/people/<id>.json (generated by scripts/extract/people.py). */
export interface Publication {
  authors?: string;
  title?: string;
  venue?: string;
  volume?: string;
  pages?: string;
  year?: string;
  url?: string;
}
export interface BookOrPatent {
  kind?: string;
  title: string;
  isbn?: string;
  publisher?: string;
  year?: string;
  authors?: string;
}
export interface Project {
  title?: string;
  agency?: string;
  role?: string;
  period?: string;
  amount?: string;
}
export interface Course {
  code: string;
  title: string;
  ltpsc: string;
  type: string;
  degree: string;
  offerings: string[];
}
export interface Activity {
  title?: string;
  body?: string;
  image?: string;
}
export interface Faculty {
  id: string;
  name: string;
  designation: string;
  photo: string;
  email: string;
  phone: string;
  address: string;
  scholar: string | null;
  website: string | null;
  otherLinks: { label: string; href: string }[];
  intro: string[];
  qualifications: string[];
  interests: string[];
  briefProfile: string[];
  publications: { journal: Publication[]; conference: Publication[]; books: BookOrPatent[]; patents: BookOrPatent[] };
  affiliations: string[];
  researchProjects: Project[];
  consultancy: Project[];
  courses: Course[];
  phdSupervised: string[];
  adminRoles: string[];
  awards: Activity[];
  events: Activity[];
  visits: Activity[];
  outreach: Activity[];
  misc: Activity[];
  studentAchievements: string[];
}
